/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/folder.glb --transform --types 
Files: ./public/folder.glb [20.02KB] > /home/toby/Projects/web-portfolio/folder-transformed.glb [2.46KB] (88%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { forwardRef } from 'react';


type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshPhysicalMaterial
  }
  //animations: GLTFAction[]
}

type myProps = JSX.IntrinsicElements['group'] & {
  color: string
  opacity: number
}



export type Ref = THREE.Group;


type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

// eslint-disable-next-line react/display-name
export const Model = forwardRef<Ref, myProps>((props, ref) => {
  const { nodes, materials } = useGLTF('/folder-transformed.glb') as GLTFResult

  const texture: THREE.Texture = new THREE.TextureLoader().load('Rolling Hills Height Map.png'); 
  
  

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh receiveShadow={true} geometry={nodes.Cube.geometry} >
        <meshPhysicalMaterial color={props.color} opacity={props.opacity} transparent iridescenceMap={texture} metalness={0.5}/>
      </mesh>
    </group>
  )
})

useGLTF.preload('/folder-transformed.glb');
